name: Metrics
on:
  # Schedule updates (every day at 0:00)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
   branches:
    - main
    - metrics
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          token: ${{ secrets.METRICS_TOKEN }}
